// SPDX-License-Identifier: GPL-2.0
//
// Generate PEBS_MARGIN for the build host by executing CPUID, writing a Rust
// source file that `exits/pebs.rs` pulls in with `include!`. Because the
// output is plain source, the same artifact works in both builds: the
// `cargo build` (compiled and run by `build.rs`) and the kernel-module build
// (compiled and run by the `all` rule in `crates/bedrock/Makefile`).
//
// Usage: gen_pebs_margin <output.rs>

use std::env;
use std::fs;

fn main() {
    let out = env::args()
        .nth(1)
        .expect("usage: gen_pebs_margin <output.rs>");

    let (family, model) = read_family_model();

    // Margins were tested on the Bitcoin workload (0 timer late injects in the
    // child VM). See `intel-family.h` in Linux for the model numbers.
    let margin: u64 = match (family, model) {
        (0x6, 0x8F) => 3, // Sapphire Rapids-SP (ex: Xeon Gold 5412U)
        (0x6, 0x6A) => 8, // Ice Lake-SP (ex: Xeon Silver 4310)
        _ => 8,           // default for untested models
    };

    let src = format!(
        "// @generated by contrib/gen_pebs_margin.rs -- do not edit.\n\
         // Build host CPU: family={family:#x} model={model:#x}\n\
         pub(crate) const PEBS_MARGIN_GENERATED: u64 = {margin};\n"
    );

    // Write only when the contents change, so an unchanged margin does not
    // bump the file's mtime and force a recompile.
    let changed = fs::read_to_string(&out).map(|cur| cur != src).unwrap_or(true);
    if changed {
        fs::write(&out, src).expect("write generated PEBS_MARGIN file");
    }
}

/// CPU family and model decoded from CPUID leaf 1 (EAX). See Intel SDM,
/// Volume 1, Chapter 21.3 CPUID Leaves, CPUID.01H -- Version and Features
fn read_family_model() -> (u32, u32) {
    use std::arch::x86_64::__cpuid;
    let eax = __cpuid(1).eax;

    let base_model = (eax >> 4) & 0xF;
    let base_family = (eax >> 8) & 0xF;
    let ext_model = (eax >> 16) & 0xF;
    let ext_family = (eax >> 20) & 0xFF;

    // When the Family ID is 06H or 0FH, this field is prepended to the Model
    // ID to provide an 8-bit model identification.
    let model = if base_family == 0x6 || base_family == 0xF {
        (ext_model << 4) | base_model
    } else {
        base_model
    };

    // When the Family ID is 0FH, this field is added to the Family ID to
    // provide an 8-bit family identification.
    let family = if base_family == 0xF {
        base_family + ext_family
    } else {
        base_family
    };

    (family, model)
}
