// SPDX-License-Identifier: GPL-2.0

//! VM exit reasons as defined in Intel SDM.

/// VM exit reasons as defined in Intel SDM Vol 3C, Appendix C.
///
/// These are the basic exit reasons (bits 15:0 of the exit reason field).
/// Bits 31:16 contain additional information (VM-entry failure, etc.).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum ExitReason {
    /// Exception or non-maskable interrupt (NMI).
    ExceptionNmi = 0,
    /// External interrupt.
    ExternalInterrupt = 1,
    /// Triple fault.
    TripleFault = 2,
    /// INIT signal.
    Init = 3,
    /// Start-up IPI (SIPI).
    Sipi = 4,
    /// I/O system-management interrupt (SMI).
    IoSmi = 5,
    /// Other SMI.
    OtherSmi = 6,
    /// Interrupt window.
    InterruptWindow = 7,
    /// NMI window.
    NmiWindow = 8,
    /// Task switch.
    TaskSwitch = 9,
    /// CPUID instruction.
    Cpuid = 10,
    /// GETSEC instruction.
    Getsec = 11,
    /// HLT instruction.
    Hlt = 12,
    /// INVD instruction.
    Invd = 13,
    /// INVLPG instruction.
    Invlpg = 14,
    /// RDPMC instruction.
    Rdpmc = 15,
    /// RDTSC instruction.
    Rdtsc = 16,
    /// RSM instruction in SMM.
    Rsm = 17,
    /// VMCALL instruction.
    Vmcall = 18,
    /// VMCLEAR instruction.
    Vmclear = 19,
    /// VMLAUNCH instruction.
    Vmlaunch = 20,
    /// VMPTRLD instruction.
    Vmptrld = 21,
    /// VMPTRST instruction.
    Vmptrst = 22,
    /// VMREAD instruction.
    Vmread = 23,
    /// VMRESUME instruction.
    Vmresume = 24,
    /// VMWRITE instruction.
    Vmwrite = 25,
    /// VMXOFF instruction.
    Vmxoff = 26,
    /// VMXON instruction.
    Vmxon = 27,
    /// Control-register accesses.
    CrAccess = 28,
    /// Debug-register accesses.
    DrAccess = 29,
    /// I/O instruction.
    IoInstruction = 30,
    /// RDMSR instruction.
    MsrRead = 31,
    /// WRMSR instruction.
    MsrWrite = 32,
    /// VM-entry failure due to invalid guest state.
    InvalidGuestState = 33,
    /// VM-entry failure due to MSR loading.
    MsrLoadFail = 34,
    /// Reserved (35).
    Reserved35 = 35,
    /// MWAIT instruction.
    Mwait = 36,
    /// Monitor trap flag.
    MonitorTrapFlag = 37,
    /// Reserved (38).
    Reserved38 = 38,
    /// MONITOR instruction.
    Monitor = 39,
    /// PAUSE instruction.
    Pause = 40,
    /// VM-entry failure due to machine-check event.
    MceDuringVmentry = 41,
    /// Reserved (42).
    Reserved42 = 42,
    /// TPR below threshold.
    TprBelowThreshold = 43,
    /// APIC access.
    ApicAccess = 44,
    /// Virtualized EOI.
    VirtualizedEoi = 45,
    /// Access to GDTR or IDTR.
    GdtrIdtrAccess = 46,
    /// Access to LDTR or TR.
    LdtrTrAccess = 47,
    /// EPT violation.
    EptViolation = 48,
    /// EPT misconfiguration.
    EptMisconfiguration = 49,
    /// INVEPT instruction.
    Invept = 50,
    /// RDTSCP instruction.
    Rdtscp = 51,
    /// VMX-preemption timer expired.
    VmxPreemptionTimer = 52,
    /// INVVPID instruction.
    Invvpid = 53,
    /// WBINVD or WBNOINVD instruction.
    Wbinvd = 54,
    /// XSETBV instruction.
    Xsetbv = 55,
    /// APIC write.
    ApicWrite = 56,
    /// RDRAND instruction.
    Rdrand = 57,
    /// INVPCID instruction.
    Invpcid = 58,
    /// VMFUNC instruction.
    Vmfunc = 59,
    /// ENCLS instruction.
    Encls = 60,
    /// RDSEED instruction.
    Rdseed = 61,
    /// Page-modification log full.
    PmlFull = 62,
    /// XSAVES instruction.
    Xsaves = 63,
    /// XRSTORS instruction.
    Xrstors = 64,
    /// PCONFIG instruction.
    Pconfig = 65,
    /// SPP-related event.
    SppRelated = 66,
    /// UMWAIT instruction.
    Umwait = 67,
    /// TPAUSE instruction.
    Tpause = 68,
    /// LOADIWKEY instruction.
    Loadiwkey = 69,
    /// Reserved (70).
    Reserved70 = 70,
    /// Reserved (71).
    Reserved71 = 71,
    /// ENQCMD PASID translation failure.
    EnqcmdPasid = 72,
    /// ENQCMDS PASID translation failure.
    EnqcmdsPasid = 73,
    /// Bus lock.
    BusLock = 74,
    /// Instruction timeout.
    InstructionTimeout = 75,
    /// SEAMCALL instruction.
    Seamcall = 76,
    /// TDCALL instruction.
    Tdcall = 77,
    /// RDMSRLIST instruction.
    Rdmsrlist = 78,
    /// WRMSRLIST instruction.
    Wrmsrlist = 79,

    // Software-generated exit reasons (not VMX hardware reasons)
    /// Scheduler needs to run (need_resched was true).
    /// This is not a VMX exit reason - it's generated by the run loop
    /// when the kernel scheduler needs to preempt VM execution.
    NeedResched = 256,
    /// Log buffer full - exit to userspace to drain.
    /// This is not a VMX exit reason - it's generated by the exit handler
    /// when the deterministic logging buffer is full.
    LogBufferFull = 257,
    /// VMCALL hypercall: shutdown.
    /// Guest requested clean VM shutdown via VMCALL with RAX=0.
    VmcallShutdown = 258,
    /// Stop-at-TSC threshold reached.
    /// The emulated TSC reached the configured stop_at_tsc value.
    StopTscReached = 259,
    /// VMCALL hypercall: snapshot.
    /// Guest requested a snapshot via VMCALL with RAX=1.
    VmcallSnapshot = 260,
    /// VMCALL hypercall: feedback buffer registered.
    /// Guest registered a feedback buffer via VMCALL with RAX=2.
    VmcallFeedbackBuffer = 261,
    /// Page pool exhausted during COW fault handling.
    /// Synthetic exit to allow refilling the page pool in sleepable context.
    PoolExhausted = 262,
    /// VMCALL hypercall: PEBS scratch page registered.
    /// Guest registered a PEBS scratch page via VMCALL with RAX=3.
    VmcallPebsPage = 263,
    /// VMCALL hypercall: I/O channel shared page registered.
    /// Guest registered the shared I/O page via VMCALL with RAX=4.
    /// Handled entirely between the guest and the kernel module — userspace
    /// continues without action.
    VmcallIoRegisterPage = 264,
    /// VMCALL hypercall: I/O channel response delivered.
    /// Guest delivered a response via VMCALL with RAX=6. Hypervisor has
    /// captured the response bytes into VmState; userspace drains them and
    /// optionally queues the next request.
    VmcallIoResponse = 265,
    /// VMCALL hypercall: guest signaled it is ready / booted / initialized.
    /// Guest issued VMCALL with RAX=7.
    VmcallReady = 266,
}

/// Error when converting from raw exit reason value.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct UnknownExitReason(pub u32);

impl TryFrom<u32> for ExitReason {
    type Error = UnknownExitReason;

    fn try_from(value: u32) -> Result<Self, Self::Error> {
        // Mask to get basic exit reason (bits 15:0)
        let basic = value & 0xFFFF;
        match basic {
            0 => Ok(Self::ExceptionNmi),
            1 => Ok(Self::ExternalInterrupt),
            2 => Ok(Self::TripleFault),
            3 => Ok(Self::Init),
            4 => Ok(Self::Sipi),
            5 => Ok(Self::IoSmi),
            6 => Ok(Self::OtherSmi),
            7 => Ok(Self::InterruptWindow),
            8 => Ok(Self::NmiWindow),
            9 => Ok(Self::TaskSwitch),
            10 => Ok(Self::Cpuid),
            11 => Ok(Self::Getsec),
            12 => Ok(Self::Hlt),
            13 => Ok(Self::Invd),
            14 => Ok(Self::Invlpg),
            15 => Ok(Self::Rdpmc),
            16 => Ok(Self::Rdtsc),
            17 => Ok(Self::Rsm),
            18 => Ok(Self::Vmcall),
            19 => Ok(Self::Vmclear),
            20 => Ok(Self::Vmlaunch),
            21 => Ok(Self::Vmptrld),
            22 => Ok(Self::Vmptrst),
            23 => Ok(Self::Vmread),
            24 => Ok(Self::Vmresume),
            25 => Ok(Self::Vmwrite),
            26 => Ok(Self::Vmxoff),
            27 => Ok(Self::Vmxon),
            28 => Ok(Self::CrAccess),
            29 => Ok(Self::DrAccess),
            30 => Ok(Self::IoInstruction),
            31 => Ok(Self::MsrRead),
            32 => Ok(Self::MsrWrite),
            33 => Ok(Self::InvalidGuestState),
            34 => Ok(Self::MsrLoadFail),
            35 => Ok(Self::Reserved35),
            36 => Ok(Self::Mwait),
            37 => Ok(Self::MonitorTrapFlag),
            38 => Ok(Self::Reserved38),
            39 => Ok(Self::Monitor),
            40 => Ok(Self::Pause),
            41 => Ok(Self::MceDuringVmentry),
            42 => Ok(Self::Reserved42),
            43 => Ok(Self::TprBelowThreshold),
            44 => Ok(Self::ApicAccess),
            45 => Ok(Self::VirtualizedEoi),
            46 => Ok(Self::GdtrIdtrAccess),
            47 => Ok(Self::LdtrTrAccess),
            48 => Ok(Self::EptViolation),
            49 => Ok(Self::EptMisconfiguration),
            50 => Ok(Self::Invept),
            51 => Ok(Self::Rdtscp),
            52 => Ok(Self::VmxPreemptionTimer),
            53 => Ok(Self::Invvpid),
            54 => Ok(Self::Wbinvd),
            55 => Ok(Self::Xsetbv),
            56 => Ok(Self::ApicWrite),
            57 => Ok(Self::Rdrand),
            58 => Ok(Self::Invpcid),
            59 => Ok(Self::Vmfunc),
            60 => Ok(Self::Encls),
            61 => Ok(Self::Rdseed),
            62 => Ok(Self::PmlFull),
            63 => Ok(Self::Xsaves),
            64 => Ok(Self::Xrstors),
            65 => Ok(Self::Pconfig),
            66 => Ok(Self::SppRelated),
            67 => Ok(Self::Umwait),
            68 => Ok(Self::Tpause),
            69 => Ok(Self::Loadiwkey),
            70 => Ok(Self::Reserved70),
            71 => Ok(Self::Reserved71),
            72 => Ok(Self::EnqcmdPasid),
            73 => Ok(Self::EnqcmdsPasid),
            74 => Ok(Self::BusLock),
            75 => Ok(Self::InstructionTimeout),
            76 => Ok(Self::Seamcall),
            77 => Ok(Self::Tdcall),
            78 => Ok(Self::Rdmsrlist),
            79 => Ok(Self::Wrmsrlist),
            _ => Err(UnknownExitReason(basic)),
        }
    }
}
